queue=[]
# queue.append(10)
# queue.append(20)
# queue.append(30)
# print(queue)
# queue.pop(0)
# print(queue)
# queue.pop(0)
# print(queue)
# queue.pop(-1)
# print(queue)

# queue.insert(0,10)
# queue.insert(0,20)
# queue.insert(0,30)
# print(queue)
# print(queue.pop())
# print(queue.pop())

print(not queue)